{% set name = "imageio-ffmpeg" %}
{% set version = "0.5.0" %}
{% set sha256 = "75c9c45079510cfeb4849a17fcd3edd4f14062ea6b69c5b62695fb2075295c87" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - setuptools
    - ffmpeg

test:
  imports:
    - imageio_ffmpeg

about:
  home: https://github.com/imageio/imageio-ffmpeg
  doc_url: https://github.com/imageio/imageio-ffmpeg
  dev_url: https://github.com/imageio/imageio-ffmpeg
  summary: FFMPEG wrapper for Python
  license: BSD 2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - anjos
    - almarklein
