{% set name = "imageio-ffmpeg" %}
{% set version = "0.5.1" %}
{% set sha256 = "0ed7a9b31f560b0c9d929c5291cd430edeb9bed3ce9a497480e536dd4326484c" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - setuptools
    - ffmpeg

test:
  requires:
    - python {{ python_min }}
  imports:
    - imageio_ffmpeg

about:
  home: https://github.com/imageio/imageio-ffmpeg
  doc_url: https://github.com/imageio/imageio-ffmpeg
  dev_url: https://github.com/imageio/imageio-ffmpeg
  summary: FFMPEG wrapper for Python
  license: BSD 2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - anjos
    - almarklein
